In [5]:
# https://www.kaggle.com/drn01z3/end-to-end-baseline-with-u-net-keras
import matplotlib.pyplot as plt
import numpy as np
import cv2
import pandas as pd
from shapely.wkt import loads as wkt_loads
#import tifffile as tiff
import os
import random
#from keras.models import Model
#from keras.layers import Input, merge, Convolution2D, MaxPooling2D, UpSampling2D, Reshape, core, Dropout
#from keras.optimizers import Adam
#from keras.callbacks import ModelCheckpoint, LearningRateScheduler
#from keras import backend as K
from sklearn.metrics import jaccard_similarity_score
from shapely.geometry import MultiPolygon, Polygon
import shapely.wkt
import shapely.affinity
from collections import defaultdict

In [7]:
coords = pd.read_csv("../feat/block_coords.csv")
coords.head()

,id,class,width,height,img_height,img_width,all_diff,block_width,block_height,block,colors,boundaries,x0,y0,x1,y1
0,0,0,4835,106,3744,5616,0,407,92,70,red,100,357.0,42.0,457.0,142.0
1,0,0,2609,309,3744,5616,0,98,269,40,red,100,48.0,219.0,148.0,319.0
2,0,0,2891,412,3744,5616,0,344,359,40,red,100,294.0,309.0,394.0,409.0
3,0,0,1823,431,3744,5616,0,501,375,20,red,100,451.0,325.0,544.0,425.0
4,0,0,3309,449,3744,5616,0,164,391,50,red,100,114.0,341.0,214.0,441.0